blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://fluxbase.eu/docs
    about: Check our documentation for answers
  - name: Discussions
    url: https://github.com/nimbleflux/fluxbase/discussions
    about: Ask questions and discuss ideas
