-- TimescaleDB Support for Logging System
--
-- This migration documents TimescaleDB support for the logging system.
-- TimescaleDB provides enhanced features for time-series log data including:
-- - Automatic time-based partitioning (hypertables)
-- - Compression of old data
-- - Automated retention policies
-- - Improved query performance for time-series data
--
-- IMPORTANT: The TimescaleDB extension is NOT created by this migration.
-- Extension creation can cause connection resets that break migration tools
-- that use advisory locks (like golang-migrate). Instead, the extension is
-- created at application runtime when needed.
--
-- See: https://docs.timescale.com/self-hosted/latest/install/

-- This migration is intentionally a no-op.
-- The application runtime code (internal/storage/log_timescaledb.go) handles
-- TimescaleDB extension creation and initialization automatically when
-- configured with:
--   logging.backend: timescaledb or postgres-timescaledb
--
-- The application will:
-- 1. Check if TimescaleDB is available (pg_available_extensions)
-- 2. Create the extension if needed (at runtime, not during migration)
-- 3. Convert logging.entries to a hypertable
-- 4. Enable compression and retention policies (if configured)
--
-- WITHOUT TIMESCALEDB:
-- If TimescaleDB is not installed, the logging system will fall back to
-- regular PostgreSQL storage using native table partitioning. All logging
-- features will work correctly, just without TimescaleDB optimizations.

-- No-op: This comment exists solely to satisfy migration tool requirements
SELECT 1 AS migration_placeholder;
